steps:
  # Install composer dependencies
  - name: 'composer:2'
    args: ['install', '--no-dev', '--optimize-autoloader']

  # Laravel configuration
  - name: 'php:8.2'
    entrypoint: php
    args:
      - -d
      - memory_limit=-1
      - artisan
      - key:generate
      - --force
      
  - name: 'php:8.2'
    entrypoint: php
    args:
      - -d
      - memory_limit=-1
      - artisan
      - config:cache
  - name: 'php:8.2'
    entrypoint: php
    args:
      - -d
      - memory_limit=-1
      - artisan
      - route:cache
  - name: 'php:8.2'
    entrypoint: php
    args:
      - -d
      - memory_limit=-1
      - artisan
      - view:cache

  # Build frontend assets if needed
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'YOUR_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/YOUR_SERVICE_NAME'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
